name: Update Readme and Assets
on:
  push:
    branches:
      - main
    paths:
      - 'readme.txt'
      - '.wordpress-org/**'

jobs:
  update:
    name: Update WordPress.org Readme and Assets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: WordPress.org Readme/Assets Update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: shayanweb-admin-fontchanger